#!/bin/bash

# enable jupyter_server_proxy
jupyter serverextension enable --sys-prefix jupyter_server_proxy

# install the flask server extension so that
# flask launches at startup
# mv flaskserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# enable bokeh extension
# jupyter serverextension enable --sys-prefix flaskserverextension
